
#Verificar se o usuário tem mais de 18 anos
idade=int(input('Qual a sua idade? '))
if idade==1:
    print('Acesso negado!')
elif idade==2:
    print('Acesso negado!')
elif idade==3:
    print('Acesso negado!')
elif idade==4:
    print('Acesso negado!')
elif idade==5:
    print('Acesso negado!')
elif idade==6:
    print('Acesso negado!')
elif idade==7:
    print('Acesso negado!')
elif idade==8:
    print('Acesso negado!')
elif idade==9:
    print('Acesso negado!')
elif idade==10:
    print('Acesso negado!')
elif idade==11:
    print('Acesso negado!')
elif idade==12:
    print('Acesso negado!')
elif idade==13:
    print('Acesso negado!')
elif idade==14:
    print('Acesso negado!')
elif idade==15:
    print('Acesso negado!')
elif idade==16:
    print('Acesso negado!')
elif idade==17:
    print('Acesso negado!')
elif idade==18:
    print('Acesso liberado!')
elif idade==19:
    print('Acesso liberado!')
elif idade==20:
    print('Acesso liberado!')
elif idade==21:
    print('Acesso liberado!')
elif idade==22:
    print('Acesso liberado!')
elif idade==23:
    print('Acesso liberado!')
elif idade==24:
    print('Acesso liberado!')
elif idade==25:
    print('Acesso liberado!')
elif idade==26:
    print('Acesso liberado!')
elif idade==27:
    print('Acesso liberado!')
elif idade==28:
    print('Acesso liberado!')
elif idade==29:
    print('Acesso liberado!')
elif idade==30:
    print('Acesso liberado!')
elif idade==3:
    print('Acesso liberado!')
